### PR TITLE
Test eliminate column

### PR DESCRIPTION
**Pull request by jova486**
### Summary
Tests for eliminate_column

### Details and comments
This should be merged to main branch

### CODE REVIEW

**Review by Pihjoe — DISMISSED** [review]
Looks good.

**Review by Alex-Elias — DISMISSED** [review]

**Comment by Aerylia** [comment]
The nature of both tests is correct, but the execution has some problems.

For `test_eliminate_column_empty_terminal_list_doesnt_return_cnots`:
The example matrix with chosen root and column does not correspond to the given list of terminals. 
I noticed from the other test, that the root will always be in the list of terminals for the permrowcol, so then the empty terminals list should never happen.
I would resolve this as follows:
- rename the test to `test_eliminate_column_identity_column`
- make the matrix a permutation matrix (identity matrix where all rows or columns are changed according to a permutation (either hardcoded or `np.random.permutation`)
- Pick an index from the permutation. The index is the root, the column is the value (or vice versa - it should have a 1 in the matrix)
- Find the terminals following the line of code in permrowcol
- Then continue as previously.

For `test_eliminate_column_doesnt_return_invalid_tuples`:
- The matrix is too small with too few 1s. The one in `test_eliminate_column_empty_terminal_list_doesnt_return_cnots` looks good.

General note for next sprint:
You might want to think about refactoring the code to have all the test done on some matrices that are generated in the `__init__()`.

**Comment by jova486** [comment]
According to aryanne's suggestion I renamed the test to test_eliminate_column_identity_column and made the proposed changes. It  does not look nice since the needed methods dont excist in this branch. I will refactor this as we get perm-row-col branch merged.

**Review by Pihjoe — COMMENTED** [review]
Should we make the privacy changes before merging, for example in tests line 133; shouldn't it be row=permrowcol._choose_row(n_vertices, parity_mat)?

**Review by MillaKelhu — APPROVED** [review]
> Should we make the privacy changes before merging, for example in tests line 133; shouldn't it be row=permrowcol._choose_row(n_vertices, parity_mat)?
I thought `choose_column()` and `choose_row()` were going to be public, because someone might want to change them, give them different heuristic, etc. 
But with `eliminate_column()` and `eliminate_row()`, right now branch `main` doesn't have those functions set private, so either the privacy of the functions will have to be changed in this branch along with the tests, or `test-eliminate-column` is merged into `main` now as is and privacy setting is done later when branch `permrowcol` is merged with `main`, since that contains the private functions and some of their tests. Personally, I'd merge `test-eliminate-column` with `main` now, and then when `permrowcol` branch is being updated up to date with `main` branch before merge, those few lines on the tests can be changed to match with the `permrowcol` branch.

**Review by Pihjoe — APPROVED** [review]

**Pull request merged**
